language: node_js
node_js: "7"
script: yarn prepush
cache:
    directories:
        - "node_modules"
deploy:
    provider: pages
    skip_cleanup: true
    github_token: f6a03dab808be537f81fd53ca3d15133f68eede9
    on:
        branch: master
notifications:
  email: false
