language: node_js
node_js: "7"
script: yarn prepush
cache:
    directories:
        - "node_modules"
dist: trusty
addons:
    apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
deploy:
    provider: pages
    skip_cleanup: true
    github_token: f6a03dab808be537f81fd53ca3d15133f68eede9
    on:
        branch: master
notifications:
  email: false
