language: node_js
node_js: "7"
script: yarn prepush
cache:
    directories:
        - "node_modules"
dist: trusty
addons:
    apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
notifications:
  email: false
  slack:
    rooms: 
      - dover-boys:HekMr2x7RnLbKn5pCAKmqnLR
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)"
      - "Repo: %{repository} - Branch: %{branch}"
      - "Build Status: %{result} in %{duration}"
      - "%{author}"
      - "%{commit}"
    on_success: always # default: always
    on_failure: always # default: always
    

