language: node_js
node_js: "7"
script: yarn prepush
cache:
    directories:
        - "node_modules"
dist: trusty
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost:80
deploy:
    provider: pages
    skip_cleanup: true
    github_token: f6a03dab808be537f81fd53ca3d15133f68eede9
    on:
        branch: master
notifications:
  email: false
